version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: sh -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./api:/api
      - ./api/vendor/bundle:/api/vendor/bundle
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true

    depends_on:
      - db
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - ./front:/src/app
    command: yarn dev -p 8000
    ports:
      - '8001:8000'
volumes:
  postgresql_data:
    driver: local